# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practical_Unlimit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FMDB', '~> 2.7.5'

end
